import {useState} from 'react';
import BurgerScrollAnimation from './BurgerScrollAnimation';

const base=location.pathname.includes('/bunzai-menu/')?'../':'./';
const image=(name:string)=>`${base}animations/burger/${name}.webp`;
const products=[
  {name:'The Original',category:'THE ONE THAT STARTED IT',price:299,description:'Smash patty, American cheese, house pickles, crisp lettuce and Bunzai sauce.',ingredients:['Smash patty','American cheese','House pickles','Bunzai sauce']},
  {name:'Bunzai Double',category:'DOUBLE DOWN',price:399,description:'Two smashed patties, double cheese, caramelised onions and our secret sauce.',ingredients:['Double patty','Double cheese','Caramelised onions','Secret sauce']},
  {name:'Firecracker',category:'BRING THE HEAT',price:349,description:'Crispy chicken, jalapeño relish, pepper jack and a hit of hot honey.',ingredients:['Crispy chicken','Jalapeño relish','Pepper jack','Hot honey']},
  {name:'Green Machine',category:'ALL GREEN. ALL GOOD.',price:299,description:'Charred veggie patty, fresh avocado, greens and bright herb mayo.',ingredients:['Veggie patty','Avocado','Fresh greens','Herb mayo']}
];
function Brand(){return <a className="brand" href={`${base}bunzai-burger.html`} aria-label="Bunzai Burger home"><span className="brand-mark">B</span><span className="brand-wordmark">BUNZAI<em>BURGERS</em></span></a>;}
function Header(){const [open,setOpen]=useState(false);return <header className="site-header"><Brand/><nav aria-label="Main navigation" className={open?'nav open':'nav'}><a href={`${base}bunzai-burger.html`} onClick={()=>setOpen(false)}>Home</a><a href={`${base}our-story.html`} onClick={()=>setOpen(false)}>Our story</a><a className="button small" href={`${base}bunzai-menu/menu.html`}>Menu <span>↗</span></a></nav><button className="nav-toggle" aria-expanded={open} aria-label={open?'Close navigation':'Open navigation'} onClick={()=>setOpen(!open)}>{open?'Close −':'Menu +'}</button></header>;}
function Hero(){return <section className="hero" id="Hero"><div className="hero-top"><p className="eyebrow">BUILT FROM THE BUN UP.</p><span className="edition">BIG FLAVOUR. ZERO SHORTCUTS.</span></div><h1>BUNZAI BURGER</h1><div className="hero-grid"><div className="hero-statement"><span className="tiny-index">GOOD THINGS / STACKED HIGH</span><h2>WE SMASH<br/><em>BETTER.</em></h2><a className="round-link" href="#product-animation" aria-label="Discover the burger layers">↓</a></div><div className="hero-product"><div className="hero-ring" aria-hidden="true"/><img src={image('poster')} alt="Sesame burger stacked with melted cheese, a seared patty, tomato and lettuce" fetchPriority="high"/><span className="product-stamp">BUNZAI<br/>BUILT DIFFERENT.</span></div><div className="hero-summary"><p>Golden edges.<br/>Melted cheese.<br/>One very good decision.</p><a className="button" href="#flavours">Find your flavour <span>↗</span></a><a className="text-link" href="#product-animation">See what’s inside <span>↓</span></a></div></div><div className="hero-bottom"><span>SMASHED. STACKED. SERVED.</span><span>SCROLL FOR THE GOOD STUFF ↓</span></div></section>;}
function Menu({full=false}:{full?:boolean}) {const [active,setActive]=useState(0);const p=products[active];return <section id="flavours" className={`menu-section section-pad ${full?'full-menu':''}`}><div className="section-topline"><span>02 / THE MENU</span><span>FOUR WAYS TO GO BIG</span></div><div className="section-heading"><h2>Explore all<br/><em>flavours.</em></h2><p>Pick your kind of bold.<br/>We’ll take care of the stack.</p></div><div className="menu-showcase"><div className="menu-art"><img src={image('poster')} alt="Illustrative Bunzai signature burger" loading="lazy"/><span className="art-label">THE BUNZAI BUILD / SERVING SUGGESTION</span></div><div className="menu-selection"><div className="product-tabs" aria-label="Select a burger">{products.map((product,i)=><button key={product.name} onClick={()=>setActive(i)} aria-pressed={i===active}><span>0{i+1}</span>{product.name}<b>{i===active?'−':'+'}</b></button>)}</div><div className="product-detail" aria-live="polite"><p className="eyebrow">{p.category}</p><div className="product-title"><h3>{p.name}</h3><span>₹{p.price}</span></div><p>{p.description}</p><div className="ingredient-tags">{p.ingredients.map(i=><span key={i}>{i}</span>)}</div><a className="button" href="#visit">Plan your visit <span>↗</span></a></div></div></div><div className="menu-footnote"><span>Prices in INR. Product image is illustrative.</span>{!full&&<a className="text-link" href={`${base}bunzai-menu/menu.html`}>Full menu ↗</a>}</div></section>;}
function ProductViewer(){const [value,setValue]=useState(0);return <section className="product-viewer section-pad" id="product-viewer"><div className="viewer-copy"><p className="eyebrow">03 / TAKE A CLOSER LOOK</p><h2>The good<br/>stuff.<br/><em>Inside out.</em></h2><p>From that first crunch to the last bite.<br/>Slide between the stack and its layers.</p><div className="viewer-options"><button aria-pressed={value===0} onClick={()=>setValue(0)}>The stack</button><button aria-pressed={value===100} onClick={()=>setValue(100)}>The layers</button></div></div><div className="viewer-display"><div className="viewer-images"><img src={image('poster')} alt={value<50?'Assembled signature burger':''} style={{opacity:1-value/100}} loading="lazy"/><img src={image('exploded')} alt={value>=50?'Separated bun, cheese, patty, tomato and lettuce layers':''} style={{opacity:value/100}} loading="lazy"/></div><label className="viewer-slider">EXPLORE THE LAYERS<input type="range" min="0" max="100" value={value} onChange={e=>setValue(Number(e.target.value))} aria-label="Blend between assembled burger and separated ingredients"/><span>ASSEMBLED <b>SEPARATED</b></span></label></div></section>;}
function Story({page=false}:{page?:boolean}){return <section id="story" className={`story-section section-pad ${page?'story-page':''}`}><div className="section-topline"><span>04 / OUR STORY</span><span>THE BUNZAI WAY</span></div><div className="story-layout"><div className="story-title"><p className="eyebrow">NOT JUST ANOTHER BURGER.</p><h2>Small details.<br/><em>Big difference.</em></h2><p>We’re here for the bite you think about later. The sear. The sauce. The way it all comes together.</p><a className="text-link" href={`${base}bunzai-menu/menu.html`}>Meet the menu ↗</a></div><div className="story-principles"><article><span>01</span><div><h3>It starts with the sear.</h3><p>A smash patty gives the Original its golden edges. Cheese brings it all together.</p></div></article><article><span>02</span><div><h3>Crunch has a place.</h3><p>Pickles and crisp lettuce bring contrast to every rich, savoury bite.</p></div></article><article><span>03</span><div><h3>Finish with flavour.</h3><p>From Bunzai sauce to hot honey, the final layer makes each burger its own.</p></div></article></div></div></section>;}
function Visit(){return <section id="visit" className="visit-section section-pad"><div><p className="eyebrow">05 / PULL UP A CHAIR</p><h2>Good food.<br/><em>Better company.</em></h2><p>Make room for your next favourite.</p></div><div className="visit-details"><h3>Find your Bunzai.</h3><dl><div><dt>LOCATION</dt><dd>Location details coming soon.</dd></div><div><dt>OPENING HOURS</dt><dd>Hours will be announced here.</dd></div><div><dt>ORDERS & RESERVATIONS</dt><dd>Online ordering and reservations are not available yet.</dd></div></dl><a className="button" href={`${base}bunzai-menu/menu.html`}>Explore the menu <span>↗</span></a></div></section>;}
function Footer(){return <><section className="final-cta"><p className="eyebrow">YOU KNOW WHAT TO DO.</p><h2>Go on.<br/><em>Go Bunzai.</em></h2><a className="button dark" href={`${base}bunzai-menu/menu.html`}>Find your next favourite <span>↗</span></a></section><footer id="footer"><div className="footer-top"><Brand/><nav aria-label="Footer navigation"><a href={`${base}bunzai-menu/menu.html`}>Menu</a><a href={`${base}our-story.html`}>Our story</a><a href="#visit">Contact & location</a><a href="#top">Back to top ↑</a></nav></div><div className="footer-word" aria-hidden="true">BUNZAI.</div><div className="footer-bottom"><span>© {new Date().getFullYear()} Bunzai Burger</span><span>BIGGER APPETITES WELCOME.</span></div></footer></>;}
export default function App(){const isMenu=location.pathname.includes('/bunzai-menu/');const isStory=location.pathname.endsWith('our-story.html');return <><a className="skip-link" href="#main">Skip to content</a><div id="top"/><Header/><main id="main">{isMenu?<><div className="subpage-title"><p className="eyebrow">THE BUNZAI MENU</p><h1>Find your<br/><em>favourite.</em></h1></div><Menu full/></>:isStory?<><div className="subpage-title"><p className="eyebrow">OUR STORY</p><h1>Built from<br/><em>the bun up.</em></h1></div><Story page/><ProductViewer/></>:<><Hero/><BurgerScrollAnimation base={base}/><Menu/><ProductViewer/><Story/></>}<Visit/></main><Footer/></>;}
